#:kivy 1.9.0

# Top bar of the app
<TopRow>:
    size_hint: (1, 0.1)
    BoxLayout:
        id: top_box
        size: root.size
        pos: root.pos
        id: boxlayout_h
        orientation: 'horizontal'
        Label:
            text: "Ankit's Crawler Feed"
        Button:
            id: sync_button
            text: 'Sync'
            group: 'test'
            on_press: root.schedule_sync()
        Button: 
            id: settings_button
            text: 'Settings'
            on_press: app.open_settings()
        Label:
            text: 'Last updated:'
            text_size: self.size
            halign: 'left'
            padding: 5, 18

<ArticleEntry>:
    orientation: 'horizontal'
    size: root.size
    pos: root.pos
    size_hint_y: None
    height: '60dp'
    Image:
        source: root.thumbnail_path
        halign:'right'
        size_hint_x: 0.3
#    width: '100dp'
    GridLayout:
        canvas.before:
            Color:
                rgb: 0.2, 0.2, 0.2
            Rectangle:
                pos: self.pos
                size: self.size

        rows: 3
        padding: 5, 2
        spacing: 1
        Label:
            text: root.title
            text_size: self.size
            halign: 'left'
        Label:
            text: root.authors
            text_size: self.size
            halign: 'left'
        ArticleLink:
            text: 'PDF'
            text_size: self.size
            halign: 'left'
            file_path: root.file_path
#    text_size: self.width, None
#    height: self.texture_size[1]
#    padding: 10, 10

#<TableHeader>:
#    size_hint_y: None
#    height: '30dp'
#    width: '100dp'
#    text_size: self.width, None
#    height: self.texture_size[1]
#    padding: 10, 10
#    canvas.before:
#        Color:
#            rgb: 0.5, 0.5, 0.5
#        Rectangle:
#            pos: self.pos
#            size: self.size

# BoxLayout for all sources:
#<SourceBoxes>:
#    height: self.minimum_height
#    size_hint_y: None

# Header for each source. Contains the source thumbnail, title, and last synced
<SourceHeader>:
    id: header
    size_hint_y: None

# Grid layout widget encompassing the header and article table
<SourceContainer>:
    height: self.minimum_height
    size_hint: (0.9, None)
    rows: 2

# Article list for a given source
<ArticleTable>:
    id: table
    cols: 1
    height:self.minimum_height
    size_hint: (1, None)            
    spacing: '1dp'

# Scroll View Widget for all the sources to sit in.
<ScrollContainer>:
    bar_color: [1, 1, 1, 1]
    do_scroll_y: 1
    SourceContainer:
        height: self.minimum_height
        id:src_box
        size_hint: 1, None
        padding: 50, 10 
        src: root.src

<ArticleCarousel>:
    direction: 'right'


RootGrid:
    TopRow:
        id: top_row
    ArticleCarousel:
        id: bottom_row
