#:kivy 1.9.0

# Top bar of the app
<TopRow>:
    size_hint: (1, 0.1)
    BoxLayout:
        id: top_box
        size: root.size
        pos: root.pos
        id: boxlayout_h
        orientation: 'horizontal'
        Label:
            text: "Ankit's Crawler Feed"
        Button:
            id: sync_button
            text: 'Sync'
            group: 'test'
            on_press: root.schedule_sync()
        Button: 
            id: settings_button
            text: 'Settings'
            on_press: app.open_settings()
        Label:
            text: 'Last updated:'
            text_size: self.size
            halign: 'left'
            padding: 5, 18

<ArticleEntry>:
#    size: root.size
    orientation: 'vertical'
#    rows: 4
    pos: root.pos
    height: self.minimum_height
    size_hint: None, None
    width: '400dp'
#    height: '600dp'
#    padding: 10, 10
    spacing: 0, 1

    Image:
        source: root.thumbnail_path
        height: '150dp'
        size_hint_y: None
    # Title
    Label:
        padding: 4, 4
        markup: True
        color: 0, 0, 0, 1
        text: '[size=18]' + root.title + '[/size]'
        text_size: root.width, None 
        size: self.texture_size
        size_hint_y: None
        halign: 'left'
        valign: 'top'
        canvas.before:
            Color:
                rgba: 0.6, 0.6, 0.8, 0.5
            Rectangle:
                pos: self.pos
                size: self.size

    Label:
        text: root.authors
        text_size: root.width, None
        size: self.texture_size
        halign: 'left'
        size_hint_y: None
        color: 0, 0, 0, 1
        canvas.before:
            Color:
                rgba: 0.7, 0.8, 0.8, 0.5
            Rectangle:
                pos: self.pos
                size: self.size


    Label:
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum tempor tortor, vitae molestie lorem mattis et. Mauris consectetur massa non metus blandit scelerisque vestibulum nec augue. Donec eu venenatis dui. Praesent consectetur facilisis justo, quis porta odio convallis sit amet. Praesent congue quam eros, malesuada feugiat velit lacinia sit amet. Integer condimentum in nibh consectetur accumsan. Aliquam erat volutpat. Morbi eget vulputate dolor, quis malesuada nisl. Ut quis tincidunt purus, quis cursus augue. Vivamus vitae pellentesque elit, a sagittis nulla. Praesent varius, magna sit amet blandit porttitor, leo mauris sodales risus, varius vehicula quam elit vitae odio.'
        padding: 4, 4
        text_size: root.width, None
        size: self.texture_size 
        size_hint_y: None
        color: 0, 0, 0, 1
        canvas.before:
            Color:
                rgba: 0.38, 0.9, 0.8, 0.5
            Rectangle:
                pos: self.pos
                size: self.size






#    text_size: self.width, None
#    height: self.texture_size[1]
#    padding: 10, 10

#<TableHeader>:
#    size_hint_y: None
#    height: '30dp'
#    width: '100dp'
#    text_size: self.width, None
#    height: self.texture_size[1]
#    padding: 10, 10
#    canvas.before:
#        Color:
#            rgb: 0.5, 0.5, 0.5
#        Rectangle:
#            pos: self.pos
#            size: self.size

# BoxLayout for all sources:
#<SourceBoxes>:
#    height: self.minimum_height
#    size_hint_y: None

# Header for each source. Contains the source thumbnail, title, and last synced
<SourceHeader>:
    id: header
    size_hint_y: None

# Grid layout widget encompassing the header and article table
<SourceContainer>:
    height: self.minimum_height
    size_hint: (1, None)
    rows: 2
    padding: 20, 50

# Article list for a given source
<ArticleTable>:
    id: table
    orientation: 'lr-tb'
    height: self.minimum_height
    size_hint: (1, None)            
    spacing: 10, 10
    padding: 10, 0, 10, 0
    target_dim: 300


# Scroll View Widget for all the sources to sit in.
<ScrollContainer>:
    bar_color: [0.2, 0.2, 0.2, 0.5]
    do_scroll_y: 1
    scroll_type: ['bars', 'content']
    scroll_speed:

# Grid Layout container for the article source carousel
# and the buttons that are used to navigate it
<ArticleCarouselContainer>:
    rows: 2

RootGrid:
    TopRow:
        id: top_row
    ArticleCarouselContainer:
        id: bottom_row
        canvas.before:
            Color:
                rgb: 1, 1, 1            
            Rectangle:
                pos: self.pos
                size: self.size